FROM php:8.3-apache

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libldap2-dev \
        libzip-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
    && docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
    && docker-php-ext-install -j"$(nproc)" \
        bcmath \
        gd \
        ldap \
        mysqli \
        pdo_mysql \
        zip \
    && rm -rf /var/lib/apt/lists/*